services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  cron:
    build: ./etl
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./etl:/app
      - ./.env:/app/.env:ro

volumes:
  pg_data: